name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.15.1

      - name: Clean node_modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install --force

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run
